PATH_UI_WELCOME_WINDOW = "UI\\Main.ui"
PATH_UI_ADMIN_WINDOW = "UI\\Admin.ui"
PATH_UI_BASKET_WINDOW = "UI\\Basket.ui"
PATH_UI_CREATOR_WINDOW = "UI\\Creator.ui"
PATH_UI_ORDERS_WINDOW = "UI\\Orders.ui"
PATH_UI_SHOP_WINDOW = "UI\\Shop.ui"


